### ISSUE TITLE
Real time IOU-tracker

### ISSUE THREAD

**Issue by hamid-mp** [JavanehBahrami/IOU_tracker#1]
Hi. I'd recenlty check your code and I realised that your code process the video in an offline manner. because, first, you read all the frames of a video and then you track the detections. Is there a way to track the detection in real-time mode using IOU-tracker?

**Comment by JavanehBahrami** [comment]
Hi @hamid-mp. 
instead of feeding video_path to the cap in `read_frames()` function:  
`(cap = cv2.VideoCapture(video_path)`

you can do this to read online frames from your camera. Then you can detect and track frame by frame:
```
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if ret:
        frame_ch = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        # here apply your detection model to give you the coordinate of boxes in the read frames, for ex:
        bbox_list, confidence_list, class_id_list = detection_model.predict(frame_ch)

        # now apply your iou_tracker to give you the ID of boxes in the read frames.
        if len(bbox_list) > 0:
            id_list = iou_tracker.track_objects(bbox_list)
            print('id_list = ', id_list)
            image = draw_bboxes(image, id_list, bbox_list)
##.....
cap.release()
```
